version: '2'
services:
  awestruct:
    build:
      context: ../../awestruct
      args:
        http_proxy: proxy01.util.phx2.redhat.com:8080
        https_proxy: proxy01.util.phx2.redhat.com:8080
    command:
      - "rake git_setup clean gen[drupal_staging]"
    volumes:
      - ../../../:/home/awestruct/developer.redhat.com
      - ../../awestruct/overlay/ssh-key:/home/awestruct/.ssh
    environment:
      - http_proxy=proxy01.util.phx2.redhat.com:8080
      - https_proxy=proxy01.util.phx2.redhat.com:8080
      - google_api_key
      - dcp_user
      - dcp_password
      - vimeo_client_secret
      - vimeo_access_token_secret
      - vimeo_access_token
      - cache_password
      - cache_url
      - site_base_path
      - site_path_suffix
      - cdn_prefix
      - cache_user
      - github_token
      - drupal_user
      - drupal_password

  drupal:
    build:
      context: ../../drupal
      args:
        http_proxy: proxy01.util.phx2.redhat.com:8080
        https_proxy: proxy01.util.phx2.redhat.com:8080
    ports:
      - "80:80"
    volumes:
      - /credentials/drupal/rhd.settings.yml:/var/www/drupal/web/sites/default/rhd.settings.yml
      - /credentials/drupal/rhd.settings.php:/var/www/drupal/web/sites/default/rhd.settings.php
      - /data/drupal/files:/var/www/drupal/web/sites/default/files
      - /data/drupal/config:/var/www/drupal/web/config/active
      - ../../../images:/var/www/drupal/web/images:ro
      - ../../../stylesheets/fonts:/var/www/drupal/web/fonts:ro
    environment:
      - http_proxy=proxy01.util.phx2.redhat.com:8080
      - https_proxy=proxy01.util.phx2.redhat.com:8080

  #
  # Environment actions
  #
  export:
    build:
      context: ../../export
      args:
        http_proxy: proxy01.util.phx2.redhat.com:8080
        https_proxy: proxy01.util.phx2.redhat.com:8080
    entrypoint: "ruby _docker/lib/export/export.rb developer-drupal.web.stage.ext.phx2.redhat.com"
    volumes:
      - /data/drupal-export:/export
      - /credentials/rsync:/home/jenkins_developer/.ssh
      - ../../../:/home/jenkins_developer/developer.redhat.com
    environment:
     - drupal.export.fail_on_missing


  rollback:
    build:
     context: ../../awestruct
     args:
      http_proxy: proxy01.util.phx2.redhat.com:8080
      https_proxy: proxy01.util.phx2.redhat.com:8080
    entrypoint: "ruby _docker/lib/rollback/rollback.rb rhd@filemgmt.jboss.org:/stg_htdocs/it-rhd-stg-main-drupal"
    volumes:
     - /data/drupal-export:/export
     - /credentials/rsync:/home/awestruct/.ssh
     - ../../../:/home/awestruct/developer.redhat.com

  #
  # Testing
  #
  unit_tests:
    build:
      context: ../../awestruct
      args:
        http_proxy: proxy01.util.phx2.redhat.com:8080
        https_proxy: proxy01.util.phx2.redhat.com:8080
    volumes:
      - ../../../:/home/awestruct/developer.redhat.com
    entrypoint: "bundle exec rake test"

  acceptance_tests:
    build: ../../awestruct
    volumes:
      - ../../../:/home/awestruct/developer.redhat.com
    environment:
      - PARALLEL_TEST
      - CUCUMBER_TAGS
      - SELENIUM_HOST=http://selhub:4444/wd/hub
      - RHD_JS_DRIVER
      - RHD_DOCKER_DRIVER
      - BUILD_URL
      - RHD_TEST_PROFILE

  docker_chrome:
    image: selenium/node-chrome-debug:2.53.0
    volumes:
      - /dev/shm:/dev/shm
      - ../../../_cucumber/tmp_downloads:/home/awestruct/developer.redhat.com/_cucumber/tmp_downloads
    environment:
      - HUB_PORT_4444_TCP_ADDR=selhub
      - DBUS_SESSION_BUS_ADDRESS=/dev/null
    depends_on:
      - selhub
    ports:
      - "5900"

  docker_firefox:
    image: selenium/node-firefox-debug:2.53.0
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - HUB_PORT_4444_TCP_ADDR=selhub
      - DBUS_SESSION_BUS_ADDRESS=/dev/null
    depends_on:
      - selhub
    ports:
      - "5900"
