version: '2'
services:
  awestruct:
    build: ../../awestruct
    entrypoint: "ruby _docker/lib/pull_request/exec_with_git_hub_status_wrapper.rb 'rake git_setup clean gen[drupal_pull_request]'"
    links:
      - drupal
    volumes:
      - ../../../:/home/awestruct/developer.redhat.com
      - ../../awestruct/overlay/ssh-key:/home/awestruct/.ssh
    environment:
      - github_status_api_token
      - github_status_context=Drupal:Drupal Site
      - github_status_repo=redhat-developer/developers.redhat.com
      - github_status_target_url=http://stumpjumper.lab4.eng.bos.redhat.com:${DRUPAL_HOST_PORT}
      - github_status_sha1=${ghprbActualCommit}
      - google_api_key
      - dcp_user
      - dcp_password
      - vimeo_client_secret
      - vimeo_access_token_secret
      - vimeo_access_token
      - cache_password
      - cache_url
      - site_base_path
      - site_path_suffix
      - cdn_prefix
      - cache_user
      - github_token
      - drupal_user
      - drupal_password
      - SEARCHISKO_HOST_PORT
      - DRUPAL_HOST_PORT
      - DRUPAL_HOST_IP
      - BUILD_URL
      - AWE_PROC_COUNT=10

  drupal:
    build: ../../drupal
    ports:
      - "80"
    links:
      - drupalmysql
    volumes:
      - ./rhd.settings.php:/var/www/drupal/web/sites/default/rhd.settings.php
      - ./rhd.settings.yml:/var/www/drupal/web/sites/default/rhd.settings.yml
      - ../../../images:/var/www/drupal/web/images:ro
      - ../../../stylesheets/fonts:/var/www/drupal/web/fonts:ro

  drupalmysql:
    image: mariadb:10.0.24
    environment:
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
      - MYSQL_DATABASE=drupal
      - MYSQL_ROOT_PASSWORD=superdupersecret
    expose:
      - "3306"
    volumes:
      - ../../drupal/prod_db.sql.gz:/docker-entrypoint-initdb.d/prod_db.sql.gz

  #
  # Environment actions
  #
  export:
   build: ../../export
   volumes:
    - ../../../:/home/jenkins_developer/developer.redhat.com
    - ../../awestruct/overlay/ssh-key:/home/jenkins_developer/.ssh
   entrypoint: "ruby _docker/lib/pull_request/exec_with_git_hub_status_wrapper.rb 'ruby _docker/lib/export/export.rb stumpjumper.lab4.eng.bos.redhat.com:${DRUPAL_HOST_PORT}'"
   network_mode: "host"
   environment:
    - github_status_api_token
    - github_status_context=Drupal:Exported Site Preview
    - github_status_repo=redhat-developer/developers.redhat.com
    - github_status_target_url=${export_destination}
    - github_status_sha1=${ghprbActualCommit}

  #
  # Testing
  #
  unit_tests:
   build: ../../awestruct
   volumes:
    - ../../../:/home/awestruct/developer.redhat.com
   entrypoint: "ruby _docker/lib/pull_request/exec_with_git_hub_status_wrapper.rb 'bundle exec rake test'"
   environment:
    - github_status_api_token
    - github_status_context=Drupal:Unit Tests
    - github_status_repo=redhat-developer/developers.redhat.com
    - github_status_target_url=${BUILD_URL}
    - github_status_sha1=${ghprbActualCommit}
    - github_status_initialise=Drupal:Unit Tests,Drupal:Acceptance Tests,Drupal:Exported Site Preview,Drupal:Blinkr,Drupal:Drupal Site

  acceptance_tests:
   build: ../../awestruct
   volumes:
     - ../../../:/home/awestruct/developer.redhat.com
   entrypoint: "ruby _docker/lib/pull_request/exec_with_git_hub_status_wrapper.rb"
   environment:
     - github_status_api_token
     - github_status_context=Drupal:Acceptance Tests
     - github_status_repo=redhat-developer/developers.redhat.com
     - github_status_target_url=${BUILD_URL}
     - github_status_sha1=${ghprbActualCommit}
     - PARALLEL_TEST
     - CUCUMBER_TAGS
     - SELENIUM_HOST=http://selhub:4444/wd/hub
     - RHD_JS_DRIVER
     - RHD_DOCKER_DRIVER
     - RHD_TEST_PROFILE

  docker_chrome:
   image: selenium/node-chrome-debug:2.53.0
   volumes:
    - /dev/shm:/dev/shm
    - ../../../_cucumber/tmp_downloads:/home/awestruct/developer.redhat.com/_cucumber/tmp_downloads
   environment:
    - HUB_PORT_4444_TCP_ADDR=selhub
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
   depends_on:
    - selhub

  docker_firefox:
   image: selenium/node-firefox-debug:2.53.0
   volumes:
    - /dev/shm:/dev/shm
    - ../../../_cucumber/tmp_downloads:/home/awestruct/developer.redhat.com/_cucumber/tmp_downloads
   environment:
    - HUB_PORT_4444_TCP_ADDR=selhub
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
   depends_on:
    - selhub
