name: OpenShift Enterprise by Red Hat
abbreviated_name: OpenShift
product_logo: portal.png
current_version: 3.3.0
product_category: application-development
customer_portal_download_url: https://rhn.redhat.com/rhn/software/channel/downloads/Download.do?cid=21355
documentation_path: OpenShift_Enterprise
full_subscription_required: true
youtube_album: https://www.youtube.com/playlist?list=PLf3vm0UK6HKo9vXQ1Ywj5tfjCUsqyXBwq
vimeo_album: https://vimeo.com/album/3555893
skip_installation_instructions: true
skip_maven_instructions: true
skip_quickstart_link: true
stackoverflow_tags:
  - openshift
  - openshift-client-tools
  - openshift-enterprise
  - openshift-cartridge
  - openshift-php-cartridges
  - openshift-gears
  - openshift-web-console
  - Openshift-env-variables
buzz_tags:
  - openshift
  - openshiftv3
index:
  desc: |
    An open, hybrid Platform-as-a-Service (PaaS) to quickly develop, host, scale, and deliver apps in the cloud.
guides:
  Release_Notes:
    formats:
      html:
        url: https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/html/2.2_Release_Notes/index.html
      html-single:
        url: https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/html-single/2.2_Release_Notes/index.html
      epub:
        url: https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/epub/2.2_Release_Notes/OpenShift_Enterprise-2-2.2_Release_Notes-en-US.epub
      pdf:
        url: https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/pdf/2.2_Release_Notes/OpenShift_Enterprise-2-2.2_Release_Notes-en-US.pdf
description: 'Develop, host, and scale your applications in the cloud.'

skip_maven_instructions: true
upstream_projects:
evaluation: https://access.redhat.com/products/openshift-enterprise-red-hat/evaluation
