version: '2'
services:
  selhub:
    image: selenium/hub
    restart: always
    expose:
      - "4444"
    ports:
      - "4444"
    privileged: true

  chrome:
     image: selenium/node-chrome-debug:2.53.0
     volumes:
      - /dev/shm:/dev/shm
      - /tmp_downloads:/tmp_downloads
     environment:
      - HUB_PORT_4444_TCP_ADDR=selhub
      - DBUS_SESSION_BUS_ADDRESS=/dev/null
     depends_on:
      - selhub
     ports:
      - "5900"
