name: Red Hat JBoss A-MQ 
abbreviated_name: JBoss A-MQ
current_version: 6.2.0.GA
documentation_path: Red_Hat_JBoss_A-MQ
product_logo: a-mq.png
intro_video: https://vimeo.com/95430180
vimeo_album: http://vimeo.com/album/2982442
youtube_album: https://www.youtube.com/playlist?list=PLf3vm0UK6HKoFt9aCQPOVt8K12fe3JaPf
index:
  desc: |
    A small-footprint, high-performance, robust messaging platform that enables real-time integration between applications, services and devices.
buzz_tags:
  - amq
  - JBoss A-MQ
guides:
  API_Reference:
     formats:
       html:
  Client_Connectivity_Guide:
  Configuring_Broker_Persistence:
  Connection_Reference:
  Console_Reference:
  Fabric_Guide:
  Fault_Tolerant_Messaging:
  Glossary:
  Installation_Guide:
  Integrating_with_JBoss_Enterprise_Application_Platform:
  JON_Performance_Metrics_Reference:
  Management_Console_User_Guide:
  Managing_and_Monitoring_a_Broker:
  Migration_Guide:
  Product_Introduction:
  Release_Notes:
    formats:
      html:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_A-MQ/6.2/html/Release_Notes/index.html
      html-single:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_A-MQ/6.2/html-single/Release_Notes/index.html
      pdf: 
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_A-MQ/6.2/pdf/Release_Notes/Red_Hat_JBoss_A-MQ-6.2-Release_Notes-en-US.pdf
      epub:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_A-MQ/6.2/epub/Release_Notes/Red_Hat_JBoss_A-MQ-6.2-Release_Notes-en-US.epub
  Security_Guide:
  Tuning_Guide:
  Using_Networks_of_Brokers:
  WS-Notification_Guide:
  XML_Configuration_Reference:
     formats:
       html:
description: 'A small-footprint, high-performance messaging platform.'
upstream_projects:
  - activemq
  - fabric8
downloads:
  6.2.1.GA:
    release_date: 2015-12-07
    description: Our small footprint, high performance, open source messaging platform
    assets:
      zip:
        size:
        name: Full Install
      zip_cpp:
        size:
        name: CMS C++ Client API
      amqp_jms_client:
        name: AMQP 1.0 JMS Client API
        size:
      cppclient:
        name: AMQP 1.0 C++ Client API
        artifacts:
          vs2012:
            name: AMQP 1.0 C++ Client x86
            size:
          vs2012_sources:
            name: AMQP 1.0 C++ Client Sources
            size:
          vs2012_64:
            name: AMQP 1.0 C++ Client 64
            size:
      net_client:
        size:
        name: NMS .NET Client API
      net_lite_sdk:
        size:
        name: AMQP 1.0 .NET Lite Client SDK
  6.2.0.GA:
    release_date: 2015-06-23
    description: Our small footprint, high performance, open source messaging platform
    assets:
      zip:
        size: 277mb
        name: Full Install
      zip_cpp:
        size: 6mb
        name: CMS C++ Client API
      amqp_jms_client:
        name: AMQP 1.0 JMS Client API
        size: 3mb
      cppclient:
        name: AMQP 1.0 C++ Client API
        artifacts:
          vs2012:
            name: AMQP 1.0 C++ Client x86
            size: 34mb
          vs2012_sources:
            name: AMQP 1.0 C++ Client Sources
            size: 1mb
          vs2012_64:
            name: AMQP 1.0 C++ Client 64
            size: 36mb
      net_client:
        size: 9mb
        name: NMS .NET Client API
      net_lite_sdk:
        size: 1mb
        name: AMQP 1.0 .NET Lite Client SDK
      net_lite_sources:
        size: 1mb
        name: AMQP 1.0 .NET Lite Client Sources
  6.1.0.GA:
    release_date: 2014-04-14
    description: Our small footprint, high performance, open source messaging platform
    assets:
      zip:
        size: 181mb
        name: Zip (Full Install)
      source:
        size: 81mb
      amqp_jms_client:
        name: AMQP JMS Client
        size: 0.79mb
      c++_client:
        size: 5.9mb
      net_client:
        size: 9.4mb
        name: .NET Client
  6.0.0.GA:
    release_date: 2013-04-10
    description: Our small footprint, high performance, open source messaging platform
    assets:
      zip:
        size: 209mb
        name: Zip (Full Install)
      fuse_ide:
        name: Fuse IDE
        artifacts:
          mac_osx:
            name: MacOS X
            size: 209mb
            filename: jboss-fuse-6.0.0.GA-fuse_ide-maxosx.zip
          win32:
            size: 210mb
            filename: jboss-fuse-6.0.0.GA-fuse_ide-win32.zip
          win64:
            size: 210mb
            filename: jboss-fuse-6.0.0.GA-fuse_ide-win64.zip
          linux32:
            size: 210mb
            filename: jboss-fuse-6.0.0.GA-fuse_ide-linux32.zip
          linux64:
            size: 210mb
            filename: jboss-fuse-6.0.0.GA-fuse_ide-linux64.zip
      release_notes:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_A-MQ/6.0/html/Release_Notes/files/front.html
      source:
        size: 64mb
demos:
  - title: Getting started with ActiveMQ
    url: https://github.com/FuseByExample/getting_started_with_activemq
    tech: ['ActiveMQ', 'Spring']
    use_case: []
    desc: "This project includes a number of example configurations showing various ActiveMQ High Availability scenarios. These include: Master-Slave, Network of Brokers, and Network of Master-Slave Brokers. This project also includes a simple JMS Queue (point to point) message producer and message consumer."
  - title: Websocket ActiveMQ Camel
    url: https://github.com/FuseByExample/websocket-activemq-camel
    tech: ['Camel', 'ActiveMQ', 'Spring', 'Jackson']
    use_case: ['Endpoint', 'Bean', 'Transform', 'Log', 'Delay']
    desc: This example shows how to use WebSocket HTML 5 with JBoss A-MQ and Camel. There are two webapps contained in this example. A stock and a news app. The news app also has a secured version over ssl. Both apps use a camel route that delivers message trough a websocket from their queue. Feeders are implemented to feed these queues.
  - title: ActiveMQ AMQP Example
    url: https://github.com/FuseByExample/activemq-amqp-example
    tech: ['ActiveMQ', 'AMQP', 'Qpid']
    use_case: []
    desc: This is an example of using Apache ActiveMQ's AMQP protocol with the Apache Qpid JMS client. It consists of a broker, producer and consumer who exchange some predefined messages. Each message will be logged by the consumer
  - title: External MQ fabric client
    url: https://github.com/FuseByExample/external-mq-fabric-client
    tech: ['Camel', 'ActiveMQ', 'Spring', 'Fabric', 'ZooKeeper']
    use_case: ['Endpoint', 'SetBody', 'Log']
    desc: This project shows how to connect to JBoss A-MQ message brokers running in Fuse Fabric from JMS clients running outside of Fuse Fabric (i.e. when the JMS client is not running within a Fabric-enabled Fuse container).
evaluation: https://access.redhat.com/products/red-hat-jboss-a-mq/evaluation
