version: '2'
services:

  tests:
   build: ../
   volumes:
    - ../../:/home/testing/developers.redhat.com
   entrypoint: ruby /home/testing/developers.redhat.com/_docker/lib/pull_request/exec_with_git_hub_status_wrapper.rb
   working_dir: /home/testing/developers.redhat.com/_cucumber
   environment:
    - github_status_enabled
    - github_status_api_token
    - github_status_context
    - github_status_repo=redhat-developer/developers.redhat.com
    - github_status_target_url=${BUILD_URL}artifact/_cucumber/reports/${RHD_TEST_PROFILE}/rhd_${RHD_TEST_PROFILE}_test_report.html
    - github_status_sha1
    - SELENIUM_HOST=http://selhub:4444/wd/hub
    - PARALLEL_TEST
    - CUCUMBER_TAGS
    - RHD_JS_DRIVER
    - RHD_TEST_PROFILE
    - RHD_DOCKER_DRIVER

  selhub:
    image: selenium/hub
    restart: always
    expose:
      - "4444"
    ports:
      - "4444"
    privileged: true
    environment:
      - GRID_BROWSER_TIMEOUT=600000
      - GRID_TIMEOUT=600000
      - SE_OPTS=-browserTimeout 300 -timeout 300

  docker_chrome:
     image: selenium/node-chrome-debug:2.53.0
     volumes:
      - /dev/shm:/dev/shm
     environment:
      - HUB_PORT_4444_TCP_ADDR=selhub
      - DBUS_SESSION_BUS_ADDRESS=/dev/null
     depends_on:
      - selhub
     ports:
      - "5900"

  docker_firefox:
     image: selenium/node-firefox-debug:2.53.0
     volumes:
      - /dev/shm:/dev/shm
     environment:
      - HUB_PORT_4444_TCP_ADDR=selhub
      - DBUS_SESSION_BUS_ADDRESS=/dev/null
     depends_on:
      - selhub
     ports:
      - "5900"