name: Red Hat Developer Toolset
abbreviated_name: Developer Toolset
product_logo: portal.png
current_version: "4.1.0"
indented_product: false
documentation_path: Red_Hat_Developer_Toolset
product_category: it-infrastructure
skip_installation_instructions: true
skip_maven_instructions: true
skip_quickstart_link: true
youtube_album: https://www.youtube.com/playlist?list=PLf3vm0UK6HKorM8sqjcTTph4Z9HWpRpim
vimeo_album: https://vimeo.com/album/3555862
customer_portal_download_url: https://access.redhat.com/downloads/content/271/ver=/rhel---7/7.1/x86_64/product-downloads
index:
  desc: |
    Get the latest stable versions of GCC (C, C++, Fortran), Eclipse, GDB, SystemTap, and essential development tools. Compiled applications are upwards compatible to run across Red Hat Enterprise Linux versions. Red Hat Developer Toolset is a part of your Red Hat Enterprise Linux subscription.
guides:
  Release_Notes:
    formats:
      html:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_Developer_Toolset/4/html/4.1_Release_Notes/index.html
      html-single:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Developer_Toolset/4/html-single/4.1_Release_Notes/index.html
      epub:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_Developer_Toolset/4/epub/4.1_Release_Notes/Red_Hat_Developer_Toolset-4-4.1_Release_Notes-en-US.epub
      pdf:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_Developer_Toolset/4/pdf/4.1_Release_Notes/Red_Hat_Developer_Toolset-4-4.1_Release_Notes-en-US.pdf
  User_Guide:
    formats:
      html:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Developer_Toolset/4/html/User_Guide/index.html
      html-single:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Developer_Toolset/4/html-single/User_Guide/index.html
      epub:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_Developer_Toolset/4/epub/User_Guide/Red_Hat_Developer_Toolset-4-User_Guide-en-US.epub
      pdf:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_Developer_Toolset/4/pdf/User_Guide/Red_Hat_Developer_Toolset-4-User_Guide-en-US.pdf
description: Bridge development agility and production stability.
downloads:
skip_maven_instructions: true
get_started_multipath: true
get_started_paths:
  - id: "cpp"
    name: Eclipse C++
    default_file: get-started-rhel7-cpp
