name: .NET Runtime for Red Hat Linux
abbreviated_name: DotNet
current_version:
product_category: application-development
skip_default_docs_and_apis: true
forum_url: https://developer.jboss.org/en/topics/dotnet
forum_desc: Build and run cross-platform .NET applications on the world's number one enterprise-ready Linux distribution, Red Hat Enterprise Linux.
index:
  desc: |
    Build and run cross-platform .NET applications on the world's number one Enterprise-ready Linux Distribution, Red Hat Enterprise Linux
description: "Build and run cross-platform .NET applications on the world's number one enterprise-ready Linux distribution, Red Hat Enterprise Linux."
