name: Red Hat .NET Runtime
abbreviated_name: DotNet
current_version:
product_category: application-development
skip_default_docs_and_apis: true
index:
  desc: |
    Build and run cross-platform .NET applications on the world's number one Enterprise-ready Linux Distribution, Red Hat Enterprise Linux
description: "Build and run cross-platform .NET applications on the world's number one Enterprise-ready Linux Distribution, Red Hat Enterprise Linux."
