name: Red Hat Container Development Kit
abbreviated_name: Container Development Kit
name_append: "For container development, includes RHEL and OpenShift 3."
product_logo:
indented_product: false
current_version:
product_category: it-infrastructure
intro_video: https://www.youtube.com/v=DGoqrqSLQtg
vimeo_album:
forum_title: Developing on Containers
forum_desc: This is a forum for those who are developing their applications in containers, and may also include discussions related to CDK, Kubernetes, docker, Vagrant, and microservices.
cdk_install_paths:
  - id: "windows"
    name: Windows
  - id: "maclinux"
    name: Mac/Linux
youtube_album: https://www.youtube.com/playlist?list=PLf3vm0UK6HKot0DBAXHKQfRDjqWKxj2mK
customer_portal_download_url: https://access.redhat.com/downloads/content/293/
index:
  desc: |
    An environment to quickly set up your environment for building secure Docker-based applications.
buzz_tags:
  - containers
guides:
  Installation_Guide:
    formats:
      html:
        url: https://access.redhat.com/documentation/en/red-hat-container-development-kit/2.1/installation-guide/installation-guide
      html-single:
        url: https://access.redhat.com/documentation/en/red-hat-container-development-kit/2.1/installation-guide/
      pdf:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_Container_Development_Kit-2.1-Installation_Guide-en-US/Red_Hat_Container_Development_Kit-2.1-Installation_Guide-en-US.pdf
      epub:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_Container_Development_Kit-2.1-Installation_Guide-en-US/Red_Hat_Container_Development_Kit-2.1-Installation_Guide-en-US.epub
  Getting_Started_Guide:
    formats:
      html:
        url: https://access.redhat.com/documentation/en/red-hat-container-development-kit/2.1/getting-started-guide/getting-started-guide
      html-single:
        url: https://access.redhat.com/documentation/en/red-hat-container-development-kit/2.1/getting-started-guide/
      pdf:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_Container_Development_Kit-2.1-Getting_Started_Guide-en-US/Red_Hat_Container_Development_Kit-2.1-Getting_Started_Guide-en-US.pdf
      epub:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_Container_Development_Kit-2.1-Getting_Started_Guide-en-US/Red_Hat_Container_Development_Kit-2.1-Getting_Started_Guide-en-US.epub
  Release_Notes_and_Known_Issues:
    formats:
      html:
        url: https://access.redhat.com/documentation/en/red-hat-container-development-kit/2.1/release-notes-and-known-issues/release-notes-and-known-issues
      html-single:
        url: https://access.redhat.com/documentation/en/red-hat-container-development-kit/2.1/release-notes-and-known-issues/
      pdf:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_Container_Development_Kit-2.1-Release_Notes_and_Known_Issues-en-US/Red_Hat_Container_Development_Kit-2.1-Release_Notes_and_Known_Issues-en-US.pdf
      epub:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_Container_Development_Kit-2.1-Release_Notes_and_Known_Issues-en-US/Red_Hat_Container_Development_Kit-2.1-Release_Notes_and_Known_Issues-en-US.epub
default_download_artifact_type: zip
description:
downloads:
upstream_projects:
featured_items:
  - image_url: http://design.jboss.org/jbossdeveloper/sitedesign/jbossdeveloper_1_0/makerfiles/images/developermaterials_datagrid.png
    url: /quickstarts/datagrid/helloworld-jdg
    text: Get started with Data Grid with this basic Infinispan example
evaluation:
skip_installation_instructions: true
skip_maven_instructions: true
get_started_multipath: false
get_started_paths:
  - id: "nodejs"
    name: Node.js
    default_file: get-started-cdk2-nodejs
  - id: "php"
    name: PHP
    default_file: get-started-cdk2-php
  - id: "python"
    name: Python
    default_file: get-started-cdk2-python
  - id: "ruby"
    name: Ruby
    default_file: get-started-cdk2-ruby
