name: Red Hat Container Development Kit
abbreviated_name: Container Development Kit
name_append: "For container development, includes RHEL and OpenShift 3."
product_logo:
indented_product: false
current_version:
product_category: it-infrastructure
other_product: true
intro_video: https://www.youtube.com/v=DGoqrqSLQtg
vimeo_album:
cdk_install_paths:
  - id: "windows"
    name: Windows
  - id: "maclinux"
    name: Mac/Linux
youtube_album: https://www.youtube.com/playlist?list=PLf3vm0UK6HKot0DBAXHKQfRDjqWKxj2mK
customer_portal_download_url: https://access.redhat.com/downloads/content/293/ver=2.1/rhel---7/2.1.0/x86_64/product-software
index:
  desc: |
    An environment to quickly set up your environment for building secure Docker-based applications.
buzz_tags:
  - containers
guides:
  CDK_2_Installation_Guide:
    formats:
      html:
        url: https://access.redhat.com/documentation/en/red-hat-enterprise-linux-atomic-host/7/container-development-kit-installation-guide/container-development-kit-installation-guide
      html-single:
        url: https://access.redhat.com/documentation/en/red-hat-enterprise-linux-atomic-host/version-7/container-development-kit-installation-guide/
      pdf:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_Enterprise_Linux_Atomic_Host-7-Container_Development_Kit_Installation_Guide-en-US/Red_Hat_Enterprise_Linux_Atomic_Host-7-Container_Development_Kit_Installation_Guide-en-US.pdf
      epub:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_Enterprise_Linux_Atomic_Host-7-Container_Development_Kit_Installation_Guide-en-US/Red_Hat_Enterprise_Linux_Atomic_Host-7-Container_Development_Kit_Installation_Guide-en-US.epub
  CDK_2_Getting_Started_Guide:
    formats:
      html:
        url: https://access.redhat.com/documentation/en/red-hat-enterprise-linux-atomic-host/7/getting-started-with-container-development-kit/getting-started-with-container-development-kit
      html-single:
        url: https://access.redhat.com/documentation/en/red-hat-enterprise-linux-atomic-host/version-7/getting-started-with-container-development-kit/
      pdf:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_Enterprise_Linux_Atomic_Host-7-Getting_Started_with_Container_Development_Kit-en-US/Red_Hat_Enterprise_Linux_Atomic_Host-7-Getting_Started_with_Container_Development_Kit-en-US.pdf
      epub:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_Enterprise_Linux_Atomic_Host-7-Getting_Started_with_Container_Development_Kit-en-US/Red_Hat_Enterprise_Linux_Atomic_Host-7-Getting_Started_with_Container_Development_Kit-en-US.epub
  CDK_2_Release_notes:
    formats:
      html:
        url: https://access.redhat.com/documentation/en/red-hat-enterprise-linux-atomic-host/7/red-hat-container-development-kit-20-release-notes/red-hat-container-development-kit-20-release-notes
      html-single:
        url: https://access.redhat.com/documentation/en/red-hat-enterprise-linux-atomic-host/version-7/red-hat-container-development-kit-20-release-notes/
      pdf:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_Enterprise_Linux_Atomic_Host-7-RedHat_ContainerDevelopmentKit2.0_Release_Notes-en-US/Red_Hat_Enterprise_Linux_Atomic_Host-7-RedHat_ContainerDevelopmentKit2.0_Release_Notes-en-US.pdf
      epub:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_Enterprise_Linux_Atomic_Host-7-RedHat_ContainerDevelopmentKit2.0_Release_Notes-en-US/Red_Hat_Enterprise_Linux_Atomic_Host-7-RedHat_ContainerDevelopmentKit2.0_Release_Notes-en-US.epub
default_download_artifact_type: zip
description:
downloads:
upstream_projects:
featured_items:
  - image_url: http://design.jboss.org/jbossdeveloper/sitedesign/jbossdeveloper_1_0/makerfiles/images/developermaterials_datagrid.png
    url: /quickstarts/datagrid/helloworld-jdg
    text: Get started with Data Grid with this basic Infinispan example
evaluation:
skip_installation_instructions: true
skip_maven_instructions: true
get_started_multipath: false
get_started_paths:
  - id: "nodejs"
    name: Node.js
    default_file: get-started-cdk2-nodejs
  - id: "php"
    name: PHP
    default_file: get-started-cdk2-php
  - id: "python"
    name: Python
    default_file: get-started-cdk2-python
  - id: "ruby"
    name: Ruby
    default_file: get-started-cdk2-ruby
