name: Red Hat Container Development Kit
abbreviated_name: Container Development Kit
product_logo: 
indented_product: true
current_version: 
intro_video: 
vimeo_album: 
youtube_album: 
index:
  desc: |
    The Red Hat Container Development Kit (CDK) simplifies the setup of your container development environment and enables you to build secure Docker-based applications.
guides:
  Release_Notes:
  Administration_and_Configuration_Guide:
  API_Documentation:
    formats:
      html:
        url: 
      html-single:
        url: 
  Developer_Guide:
  Getting_Started_Guide:
  Infinispan_Query_Guide:
default_download_artifact_type: zip
description:
downloads:
upstream_projects:
featured_items:
  - image_url: http://design.jboss.org/jbossdeveloper/sitedesign/jbossdeveloper_1_0/makerfiles/images/developermaterials_datagrid.png
    url: /quickstarts/datagrid/helloworld-jdg
    text: Get started with Data Grid with this basic Infinispan example
evaluation: 
skip_installation_instructions: true
skip_maven_instructions: true
