name: Red Hat Container Development Kit
abbreviated_name: Container Development Kit
product_logo: 
indented_product: true
current_version: 
product_category: it-infrastructure
intro_video: https://www.youtube.com/v=DGoqrqSLQtg 
vimeo_album: 
youtube_album: 
index:
  desc: |
    Quickly setup your development environment for building secure Docker-based applications.
buzz_tags:
  - containers
guides:
  RHEL_Guide:
    formats:
      html:
        url: https://access.redhat.com/documentation/en/red-hat-enterprise-linux-atomic-host/7/container-development-kit-guide/container-development-kit-guide
      html-single:
        url: https://access.redhat.com/documentation/en/red-hat-enterprise-linux-atomic-host/version-7/container-development-kit-guide
      pdf:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_Enterprise_Linux_Atomic_Host-7-Container_Development_Kit_Guide-en-US/Red_Hat_Enterprise_Linux_Atomic_Host-7-Container_Development_Kit_Guide-en-US.pdf
      epub:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_Enterprise_Linux_Atomic_Host-7-Container_Development_Kit_Guide-en-US/Red_Hat_Enterprise_Linux_Atomic_Host-7-Container_Development_Kit_Guide-en-US.epub
  Mac_OS_X_Guide:
    formats:
      html:
        url: https://access.redhat.com/documentation/en/red-hat-enterprise-linux-atomic-host/7/container-development-kit-guide/container-development-kit-guide
      html-single:
        url: https://access.redhat.com/documentation/en/red-hat-enterprise-linux-atomic-host/version-7/container-development-kit-guide
      pdf:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_Enterprise_Linux_Atomic_Host-7-Container_Development_Kit_Guide-en-US/Red_Hat_Enterprise_Linux_Atomic_Host-7-Container_Development_Kit_Guide-en-US.pdf
      epub:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_Enterprise_Linux_Atomic_Host-7-Container_Development_Kit_Guide-en-US/Red_Hat_Enterprise_Linux_Atomic_Host-7-Container_Development_Kit_Guide-en-US.epub
  Windows_Guide:
    formats:
      html:
        url: https://access.redhat.com/documentation/en/red-hat-enterprise-linux-atomic-host/7/container-development-kit-guide/container-development-kit-guide
      html-single:
        url: https://access.redhat.com/documentation/en/red-hat-enterprise-linux-atomic-host/version-7/container-development-kit-guide
      pdf:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_Enterprise_Linux_Atomic_Host-7-Container_Development_Kit_Guide-en-US/Red_Hat_Enterprise_Linux_Atomic_Host-7-Container_Development_Kit_Guide-en-US.pdf
      epub:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_Enterprise_Linux_Atomic_Host-7-Container_Development_Kit_Guide-en-US/Red_Hat_Enterprise_Linux_Atomic_Host-7-Container_Development_Kit_Guide-en-US.epub
  Fedora_23_Guide:
    formats:
      html:
        url: https://access.redhat.com/documentation/en/red-hat-enterprise-linux-atomic-host/7/container-development-kit-guide/container-development-kit-guide
      html-single:
        url: https://access.redhat.com/documentation/en/red-hat-enterprise-linux-atomic-host/version-7/container-development-kit-guide
      pdf:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_Enterprise_Linux_Atomic_Host-7-Container_Development_Kit_Guide-en-US/Red_Hat_Enterprise_Linux_Atomic_Host-7-Container_Development_Kit_Guide-en-US.pdf
      epub:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_Enterprise_Linux_Atomic_Host-7-Container_Development_Kit_Guide-en-US/Red_Hat_Enterprise_Linux_Atomic_Host-7-Container_Development_Kit_Guide-en-US.epub
default_download_artifact_type: zip
description:
downloads:
upstream_projects:
featured_items:
  - image_url: http://design.jboss.org/jbossdeveloper/sitedesign/jbossdeveloper_1_0/makerfiles/images/developermaterials_datagrid.png
    url: /quickstarts/datagrid/helloworld-jdg
    text: Get started with Data Grid with this basic Infinispan example
evaluation: 
skip_installation_instructions: true
skip_maven_instructions: true
get_started_multipath: true
hide_rhel_tabs: true
get_started_paths:
  - id: "nodejs"
    name: Node.js
    default_file: get-started-nodejs
  - id: "php"
    name: PHP
    default_file: get-started-php
  - id: "python"
    name: Python
    default_file: get-started-python
  - id: "ruby"
    name: Ruby
    default_file: get-started-ruby
