name: Red Hat Enterprise Linux
abbreviated_name: RHEL
name_append:  "For traditional development, includes Software Collections and Developer Toolset."
product_logo: portal.png
current_version: 7.0.0.GA
product_category: it-infrastructure
documentation_path: Red_Hat_Enterprise_Linux
youtube_album: https://www.youtube.com/playlist?list=PLf3vm0UK6HKqLP5eJxZJIZJXtSk-neHhH
vimeo_album: https://vimeo.com/album/3555906
skip_installation_instructions: true
skip_maven_instructions: true
skip_quickstart_link: true
skip_default_docs_and_apis: true
buzz_tags:
  - rhel
  - rhel7
  - red hat enterprise linux
index:
  desc:
    The leading enterprise operating system to speed application delivery across physical, virtual, and cloud environments.
description: 'The world’s leading enterprise Linux platform'
skip_maven_instructions: true
other_product: true
upstream_projects:
  - fedora
rhel_install_paths:
  - id: "bare-metal"
    name: Bare Metal
  - id: "hyper-v"
    name: Hyper-V
  - id: "kvm"
    name: KVM    
  - id: "virtualbox"
    name: VirtualBox
  - id: "vmware"
    name: VMware
get_started_paths:
  - id: "cpp"
    name: C++
    default_file: get-started-rhel7-cpp
  - id: "java"
    name: Java
    default_file: get-started-rhel7-java
  - id: "perl"
    name: Perl
    default_file: get-started-rhel7-perl
  - id: "php"
    name: PHP
    default_file: get-started-rhel7-php
  - id: "python"
    name: Python
    default_file: get-started-rhel7-python
  - id: "ruby"
    name: Ruby
    default_file: get-started-rhel7-ruby
