name: Red Hat JBoss Developer Studio
abbreviated_name: JBoss Developer Studio
product_logo: developer-studio.png
current_version: 10.0.0.GA
product_category: application-development
intro_video: https://vimeo.com/95444954
vimeo_album: http://vimeo.com/album/2982449
youtube_album: https://www.youtube.com/playlist?list=PLf3vm0UK6HKrxJ9OtX2Zmgw3nyeYs0QGR
buzz_tags:
  - jbds
  - JBoss DevStudio
index:
  desc: |
    An Eclipse-based IDE to create apps for web, mobile, transactional enterprise, and SOA-based integration apps/services.
guides:
  Release_Notes:
    formats:
      html:
        url: https://access.redhat.com/articles/2361531
  Install_Red_Hat_JBoss_Developer_Studio:
    formats:
      html:
        url: https://access.redhat.com/articles/2358611
  Update_Red_Hat_JBoss_Developer_Studio:
    formats:
      html:
        url: https://access.redhat.com/articles/2360061
default_download_artifact_type: jar_universal
description: 'A development environment with superior support for your entire development lifecycle.'
upstream_projects:
  - jbosstools
featured_items:
  - image_url: http://design.jboss.org/jbossdeveloper/sitedesign/jbossdeveloper_1_0/makerfiles/images/developermaterials_devstudio.png
    url: /video/vimeo/92554627
evaluation: https://access.redhat.com/products/red-hat-jboss-developer-studio/evaluation
