version: '2.1'
services:
  rhd_e2e_testing:
    build:
      context: '..'
    shm_size: '3gb'
    user: '1000'
    volumes:
    - ../../../:/developers.redhat.com
    - ../tmp_downloads:/testing/tmp_downloads
    - ../report:/testing/report
    entrypoint:
    - '/bin/bash'
    - '-c'
    - "source /etc/scl_enable && ./wait-for-docker-selenium.sh"
    working_dir: /testing
    environment:
    - github_status_enabled
    - github_status_api_token
    - github_status_context
    - github_status_repo=redhat-developer/developers.redhat.com
    - github_status_target_url=${BUILD_URL}artifact/_tests/e2e/report/${RHD_TEST_PROFILE}-report/index.html
    - github_status_sha1
    - RHD_JS_DRIVER
    - RHD_BASE_URL
    - RHD_TEST_PROFILE
    - RHD_TEST_TAGS
    - RHD_DRUPAL_ADMIN_USERNAME
    - RHD_DRUPAL_ADMIN_PASSWORD
    - RHD_KEYCLOAK_ADMIN_USERNAME
    - RHD_KEYCLOAK_ADMIN_PASSWORD
    - GRID_HOST=chrome
    - GRID_PORT=4444
    - https_proxy
    - http_proxy

  chrome:
    image: selenium/standalone-chrome:3.141.0-actinium
    volumes:
    - /dev/shm:/dev/shm
    - ../tmp_downloads:/testing/tmp_downloads
    ports:
    - 4444:4444
    links:
    - rhd_e2e_testing