version: '2'
services:
  rhd_e2e_testing:
    build: ../
    volumes:
      - ../../../:/home/e2e/developers.redhat.com
    entrypoint: ruby /home/e2e/developers.redhat.com/_docker/lib/pull_request/exec_with_git_hub_status_wrapper.rb
    working_dir: /home/e2e/developers.redhat.com/_tests/e2e
    environment:
      - github_status_enabled
      - github_status_api_token
      - github_status_context
      - github_status_repo=redhat-developer/developers.redhat.com
      - github_status_target_url=${BUILD_URL}/testReport
      - github_status_sha1
      - RHD_BS_AUTHKEY
      - RHD_BS_USERNAME
      - NODE_SELENIUM_HOST=selhub
      - RHD_JS_DRIVER
      - RHD_VERBOSE_OUTPUT
      - CUCUMBER_TAGS

  selhub:
    image: selenium/hub:3.4.0-einsteinium
    restart: always
    expose:
      - "4444"
    ports:
      - "4444"
    privileged: true
    environment:
      - GRID_BROWSER_TIMEOUT=600000
      - GRID_TIMEOUT=600000
      - SE_OPTS=-browserTimeout 300 -timeout 300

  chrome:
     image: selenium/node-chrome:3.4.0-einsteinium
     volumes:
      - /dev/shm:/dev/shm
     environment:
      - HUB_PORT_4444_TCP_ADDR=selhub
      - HUB_PORT_4444_TCP_PORT=4444
      - DBUS_SESSION_BUS_ADDRESS=/dev/null
     depends_on:
      - selhub
     ports:
      - "5900"

  firefox:
     image: selenium/node-firefox:3.4.0-einsteinium
     volumes:
      - /dev/shm:/dev/shm
     environment:
      - HUB_PORT_4444_TCP_ADDR=selhub
      - HUB_PORT_4444_TCP_PORT=4444
      - DBUS_SESSION_BUS_ADDRESS=/dev/null
     depends_on:
      - selhub
     ports:
      - "5900"