<% sitemap_loc = "#{File.dirname(File.expand_path('.', __FILE__))}/critical-links-sitemap.xml" %>
base_url: https://developers.redhat.com
custom_sitemap: <%= sitemap_loc %>
verbose: true
max_page_retys: 5
max_retrys: 5
browser: phantomjs
ignore_fragments: true
phantomjs_threads: 8
report: blinkr.html
