name: Red Hat Application Migration Toolkit
abbreviated_name: RHAMT
product_category: it-infrastructure
ignore_forums: true
index:
  desc: |
    Red Hat Application Migration Toolkit is an assembly of open source tools that enables large-scale application migrations and modernizations. The tooling consists of multiple individual components that provide support for each phase of a migration process.
