name: Red Hat JBoss Web Server
abbreviated_name: JBoss Web Server
product_logo: web-server.png
documentation_path: JBoss_Enterprise_Web_Server
full_subscription_required: true
documentation_minor_version: 2
current_version: 2.0.0
product_category: application-development
skip_quickstart_link: true
vimeo_album: http://vimeo.com/album/2982377
youtube_album: https://www.youtube.com/playlist?list=PLf3vm0UK6HKr36iX74VAYDXwtjkanCDlT
description: A web server that combines market-leading open source technologies with enterprise capabilities to provide a single solution for large-scale websites and light-weight Java web applications.
stackoverflow_tags:
  - jboss-web
index:
  desc: |
    Apache httpd, Tomcat, etc. to provide a single solution for large-scale websites and light-weight Java web applications.
customer_portal_download_url: https://access.redhat.com/jbossnetwork/restricted/listSoftware.html?downloadType=distributions&product=webserver&productChanged=yes
guides:
  Release_Notes:
    formats:
      html:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Web_Server/2/html/2.0.0_Release_Notes/index.html
      html-single:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Web_Server/2/html-single/2.0.0_Release_Notes/index.html
      pdf:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Web_Server/2/pdf/2.0.0_Release_Notes/Red_Hat_JBoss_Web_Server-2-2.0.0_Release_Notes-en-US.pdf
      epub:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Web_Server/2/epub/2.0.0_Release_Notes/Red_Hat_JBoss_Web_Server-2-2.0.0_Release_Notes-en-US.epub
  Hibernate_Core_Guide:
    formats:
      html:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Web_Server/2/html/Hibernate_Core_Guide/index.html
      html-single:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Web_Server/2/html-single/Hibernate_Core_Guide/index.html
      pdf:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Web_Server/2/pdf/Hibernate_Core_Guide/Red_Hat_JBoss_Web_Server-2-Hibernate_Core_Guide-en-US.pdf
      epub:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Web_Server/2/epub/Hibernate_Core_Guide/Red_Hat_JBoss_Web_Server-2-Hibernate_Core_Guide-en-US.epub
  HTTP_Connectors_Load_Balancing_Guide:
    formats:
      html:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Web_Server/2/html/HTTP_Connectors_Load_Balancing_Guide/index.html
      html-single:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Web_Server/2/html-single/HTTP_Connectors_Load_Balancing_Guide/index.html
      pdf:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Web_Server/2/pdf/HTTP_Connectors_Load_Balancing_Guide/Red_Hat_JBoss_Web_Server-2-HTTP_Connectors_Load_Balancing_Guide-en-US.pdf
      epub:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Web_Server/2/epub/HTTP_Connectors_Load_Balancing_Guide/Red_Hat_JBoss_Web_Server-2-HTTP_Connectors_Load_Balancing_Guide-en-US.epub
  Installation_Guide:
    formats:
      html:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Web_Server/2/html/Installation_Guide/index.html
      html-single:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Web_Server/2/html-single/Installation_Guide/index.html
      pdf:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Web_Server/2/pdf/Installation_Guide/Red_Hat_JBoss_Web_Server-2-Installation_Guide-en-US.pdf
      epub:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Web_Server/2/epub/Installation_Guide/Red_Hat_JBoss_Web_Server-2-Installation_Guide-en-US.epub
downloads:
upstream_projects:
  - tomcat
  - httpd
  - mod_cluster
evaluation: https://access.redhat.com/products/red-hat-jboss-web-server/evaluation
