name: Red Hat JBoss Web Server
abbreviated_name: JBoss Web Server
product_logo: web-server.png
documentation_path: JBoss_Enterprise_Web_Server
documentation_minor_version: 2
current_version: 2.0.0.GA
vimeo_album: http://vimeo.com/album/2982377
description: A web server that combines market-leading open source technologies with enterprise capabilities to provide a single solution for large-scale websites and light-weight Java web applications.
guides:
  Release_Notes:
  Hibernate_Core_Guide:
  HTTP_Connectors_Load_Balancing_Guide:
  Installation_Guide:
downloads:
upstream_projects:
  - tomcat
  - httpd
  - mod_cluster

