name: Red Hat JBoss Data Grid
abbreviated_name: JBoss Data Grid
product_logo: data-grid.png
current_version: 6.5.0.GA
intro_video: https://vimeo.com/95291413
vimeo_album: http://vimeo.com/album/2982379
youtube_album: https://www.youtube.com/playlist?list=PLf3vm0UK6HKqNQqGC2KitIx4eMsEVWBaQ
index:
  desc: |
    An in-memory data grid to accelerate application performance by offering fast, distributed data access, elastic scalability, and independence from the traditional data tier.
guides:
  Release_Notes:
  Administration_and_Configuration_Guide:
  API_Documentation:
    formats:
      html:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_Data_Grid/6.5/html/API_Documentation/index.html
      html-single:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_Data_Grid/6.5/html-single/API_Documentation/index.html  
  Developer_Guide:
  Getting_Started_Guide:
  Infinispan_Query_Guide:
default_download_artifact_type: zip
description: 'An intelligent, distributed caching solution that boosts application performance, provides greater deployment flexibility, and minimizes the overhead of standing up new applications.'
downloads:
  6.5.0.GA:
    release_date: 2015-06-17
    description: An in-memory distributed database, Red Hat JBoss Data Grid provides fast access to data and elastic scalability for large data volumes.
    assets:
      zip:
        size: 158mb
        name: Data Grid Server
      zip_library:
        size: 39mb
        name: Data Grid Library
      eap_module:
        size: 3mb
        name: JBoss EAP Module for Hotrod Java Client
      eap_library:
        size: 27mb
        name: JBoss EAP Module for Data Grid Library
      java_client:
        size: 4mb
        name: Hot Rod Java Client
      cppclient:
        name: Hot Rod C++ Client
        artifacts:
          win64:
            name: C++ Client Win64
            size: 4mb
          rhel7_64:
            name: C++ Client RHEL7_64
            size: 1mb
          rhel6_64:
            name: C++ Client RHEL6_64
            size: 1mb
          rhel5_64:
            name: C++ Client RHEL5_64
            size: 1mb
          source:
            name: Source
            size: 303kb
      dotnetclient:
        name: Hot Rod .Net Client
        artifacts:
          DotNet:
            name: Hot Rod .Net Client
            size: 1mb
            type: msi
          DotNetSource:
            name: Hot Rod .Net Source
            size: 174kb
      jdbc_migrator:
        size: 7mb
        name: JDBC Migrator from 6.1
      jon_server:
        size: 1mb
        name: JON Server Plugin
      jon_library:
        size: 1mb
        name: JON Library Plugin        
      quickstarts:
        size: 2mb
        name: Quickstarts
      camel_library:
        size: 1mb
        name: Camel Component for JBoss Fuse
      maven_repo:
        size: 453mb
        name: Maven Repository
      source:
        size: 40mb
      release_notes:
  6.5.0.Beta:
    release_date: 2015-05-07
    description: An in-memory distributed database, Red Hat JBoss Data Grid provides fast access to data and elastic scalability for large data volumes.
    assets:
      zip:
        size: 158mb
        name: Data Grid Server
      zip_library:
        size: 38mb
        name: Data Grid Library
      eap_module:
        size: 3mb
        name: JBoss EAP Module for Hotrod Java Client
      eap_library:
        size: 27mb
        name: JBoss EAP Module for Data Grid Library
      java_client:
        size: 4mb
        name: Hot Rod Java Client
      cppclient:
        name: Hot Rod C++ Client
        artifacts:
          win64:
            name: C++ Client Win64
            size: 4mb
          rhel7_64:
            name: C++ Client RHEL7_64
            size: 1mb
          rhel6_64:
            name: C++ Client RHEL6_64
            size: 1mb
          rhel5_64:
            name: C++ Client RHEL5_64
            size: 1mb
          source:
            name: Source
            size: 303kb
      dotnetclient:
        name: Hot Rod .Net Client
        artifacts:
          DotNet:
            name: Hot Rod .Net Client
            size: 1mb
            type: msi
          DotNetSource:
            name: Hot Rod .Net Source
            size: 174kb
      quickstarts:
        size: 2mb
        name: Quickstarts
      camel_library:
        size: 1mb
        name: Camel Component for JBoss Fuse
      maven_repo:
        size: 432mb
        name: Maven Repository
      source:
        size: 40mb
      release_notes:
  6.4.0.GA:
    release_date: 2015-01-27
    description: An in-memory distributed database, Red Hat JBoss Data Grid provides fast access to data and elastic scalability for large data volumes.
    assets:
      zip:
        size: 165mb
        name: Data Grid Server
      zip_library:
        size: 37mb
        name: Data Grid Library
      eap_module:
        size: 2mb
        name: JBoss EAP Module for Hotrod Java Client
      eap_library:
        size: 23mb
        name: JBoss EAP Module for Data Grid Library
      java_client:
        size: 4mb
        name: Hot Rod Java Client
      cppclient:
        name: Hot Rod C++ Client
        artifacts:
          win32:
            name: C++ Client Win32
            size: 4mb
          win64:
            name: C++ Client Win64
            size: 4mb
          rhel6_64:
            name: C++ Client RHEL6_64
            size: 1mb
          rhel5_64:
            name: C++ Client RHEL5_64
            size: 1mb
          source:
            name: Source
            size: 600kb
      dotnetclient:
        name: Hot Rod .Net Client
        artifacts:
          DotNet:
            name: Hot Rod .Net Client
            size: 1mb
            type: msi
          DotNetSource:
            name: Hot Rod .Net Source
            size: 161kb
      quickstarts:
        size: 1mb
        name: Quickstarts
      camel_library:
        size: 1mb
        name: Camel Component for JBoss Fuse
      maven_repo:
        size: 149mb
        name: Maven Repository
      source:
        size: 38mb
      release_notes:
  6.4.0.Beta:
    release_date: 2014-11-18
    description: An in-memory distributed database, Red Hat JBoss Data Grid provides fast access to data and elastic scalability for large data volumes.
    assets:
      zip:
        size: 164mb
        name: Data Grid Server
      zip_library:
        size: 37mb
        name: Data Grid Library
      eap_module:
        size: 2mb
        name: JBoss EAP Module for Hotrod Java Client
      eap_library:
        size: 22mb
        name: JBoss EAP Module for Data Grid Library
      java_client:
        size: 2mb
        name: Hot Rod Java Client
      cppclient:
        name: Hot Rod C++ Client
        artifacts:
          win32:
            name: C++ Client Win32
            size: 4mb
          win64:
            name: C++ Client Win64
            size: 4mb
          rhel6_64:
            name: C++ Client RHEL6_64
            size: 1mb
          rhel5_64:
            name: C++ Client RHEL5_64
            size: 1mb
          source:
            name: Source
            size: 610kb
      dotnetclient:
        name: Hot Rod .Net Client
        artifacts:
          DotNet:
            name: Hot Rod .Net Client
            size: 1mb
            type: msi
          DotNetSource:
            name: Hot Rod .Net Source
            size: 1mb
      quickstarts:
        size: 1mb
        name: Quickstarts
      camel_library:
        size: 1mb
        name: Camel Library
      maven_repo:
        size: 141mb
        name: Maven Repository
      source:
        size: 38mb
      release_notes:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_Data_Grid/6.4/html/6.4.0_Release_Notes
  6.3.0.GA:
    release_date: 2014-07-21
    description: An in-memory distributed database, Red Hat JBoss Data Grid provides fast access to data and elastic scalability for large data volumes.
    assets:
      zip:
        size: 133mb
        name: Data Grid Server
      zip_library:
        size: 41mb
        name: Data Grid Library
      eap_module:
        size: 2mb
        name: JBoss EAP Module for Hotrod Java Client
      eap_library:
        size: 22mb
        name: JBoss EAP Module for Data Grid Library
      java_client:
        size: 2mb
        name: Hot Rod Java Client
      cppclient:
        name: Hot Rod C++ Client
        artifacts:
          win32:
            name: C++ Client Win32
            size: 3mb
          win64:
            name: C++ Client Win64
            size: 4mb
          rhel6_64:
            name: C++ Client RHEL6_64
            size: 1mb
          rhel5_64:
            name: C++ Client RHEL5_64
            size: 1mb
          source:
            name: Source
            size: 610kb
      dotnetclient:
        name: Hot Rod .Net Client
        artifacts:
          DotNet:
            name: Hot Rod .Net Client
            size: 1mb
            type: msi
          DotNetSource:
            name: Hot Rod .Net Source
            size: 1mb
      maven_repo:
        size: 72mb
        name: Maven Repository
      quickstarts:
        size: 1mb
        name: Quickstarts
      source:
        size: 9mb
      release_notes:
  6.2.0.GA:
    release_date: 2014-01-15
    description: An in-memory distributed database, Red Hat JBoss Data Grid provides fast access to data and elastic scalability for large data volumes.
    assets:
      zip:
        size: 133mb
        name: Data Grid Server
      zip_library:
        size: 41mb
        name: Data Grid Library
      cppclient:
        name: Hot Rod C++ Client
        artifacts:
          win32:
            name: C++ Client Win32
            size: 3mb
          win64:
            name: C++ Client Win64
            size: 4mb
          rhel6_64:
            name: C++ Client RHEL6_64
            size: 1mb
          rhel5_64:
            name: C++ Client RHEL5_64
            size: 1mb
      source:
        size: 9mb
      release_notes:
upstream_projects:
  - infinispan
  - jgroups
  - hibernate_subprojects_search
featured_items:
  - image_url: http://design.jboss.org/jbossdeveloper/sitedesign/jbossdeveloper_1_0/makerfiles/images/developermaterials_datagrid.png
    url: /quickstarts/datagrid/helloworld-jdg
    text: Get started with Data Grid with this basic Infinispan example
evaluation: https://access.redhat.com/products/red-hat-jboss-data-grid/evaluation
