name: Red Hat Mobile Application Platform
abbreviated_name: Mobile Application Platform
current_version: 1.0.0.GA
intro_youtube: https://www.youtube.com/v=Dw-Z-R2C51U
youtube_album: https://www.youtube.com/playlist?list=PLf3vm0UK6HKroZy6oqmmS1uBXRbq8QiS9
skip_installation_instructions: true
skip_maven_instructions: true
skip_quickstart_link: true
description: Red Hat Mobile Application Platform enables you to develop and deploy mobile apps in an agile and flexible manner.
index:
  desc: |
    Red Hat Mobile Application Platform enables you to develop and deploy mobile apps in an agile and flexible manner.
guides:
downloads:
other_product: true
