name: Red Hat JBoss BRMS
abbreviated_name: JBoss BRMS
product_logo: brms.png
has_installer: false
current_version: 6.0.2.GA
documentation_minor_version: 6.0
intro_video: https://vimeo.com/95600665
vimeo_album: http://vimeo.com/album/2982444
youtube_album: http://www.youtube.com/playlist?list=PLcrLvMVKO0b377pxbjvepIBuoQl7lcEiK
skip_installation_instructions: true
skip_maven_instructions: true
guides: 
  Business_Resource_Planner_Guide:
  Getting_Started_Guide:
  Release_Notes:
    formats:
      html: 
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_BRMS/6.0/html/6.0.2_Release_Notes/index.html
      html-single:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_BRMS/6.0/html-single/6.0.2_Release_Notes/index.html
      pdf:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_BRMS/6.0/pdf/6.0.2_Release_Notes/Red_Hat_JBoss_BRMS-6.0-6.0.2_Release_Notes-en-US.pdf
      epub: 
        url: https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_BRMS/6.0/pdf/6.0.2_Release_Notes/Red_Hat_JBoss_BRMS-6.0-6.0.2_Release_Notes-en-US.pdf
  User_Guide:
default_download_artifact_type: installer
description: 'A rule-based programming platform built on Drools Expert, Drools Guvnor, and Drools Fusion that allows users to capture rules that can be easily modified as the business changes without impacting static applications.'
downloads:
  # 6.0.2 is an exclusion to the "no micros through $0 dev program
  6.0.2.GA:
    description: Red Hat JBoss BRMS 6.0.2 is an incremental bug fix release over the 6.0.1 version.
    tag_line: This release brings in 250+ bug fixes, support for IBM Websphere, certification on RHEL7 and several new quick starts.
    release_date: 2014-06-30
    assets:
      installer:
        size: 265mb
      zip:
        artifacts:
          deployable:
            size: 140mb
      maven_repo:
        size: 142mb
        name: Maven Repository
        filename: bpms-brms-6.0.2.GA-redhat-5-maven-repository.zip
      zip_planner:
        size: 53mb
        name: Optaplanner
        filename: jboss-bpmsuite-6.0.2.GA-zip_planner.zip
      release_notes:
      source:
        size: 150mb
        filename: jboss-bpmsuite-6.0.2.GA-source.zip
  # 6.0.1 is an exclusion to the "no micros through $0 dev program
  6.0.1.GA:
    release_date: 2014-04-03
    description: A business process and decision management platform that combines Drools Expert, Drools Guvnor, Drools Fusion and JBoss jBPM in a single integrated distribution.
    assets:
      installer:
        size: 272mb
      zip:
        artifacts:
          deployable:
            size: 221mb
      maven_repo:
        size: 280mb
        name: Maven Repository
        filename: jboss-bpmsuite-6.0.1.GA-maven_repo.zip
      zip_planner:
        size: 55mb
        name: Optaplanner
        filename: jboss-bpmsuite-6.0.1.GA-zip_planner.zip
      release_notes:
      source:
        size: 177mb
        filename: jboss-bpmsuite-6.0.1.GA-source.zip
  6.0.0.GA:
    release_date: 2014-02-05
    description: A business process and decision management platform that combines Drools Expert, Drools Guvnor, Drools Fusion and JBoss jBPM in a single integrated distribution.
    assets:
      installer:
        size: 258mb
      zip:
        artifacts:
          deployable:
            size: 174mb
      zip_planner:
        size: 55mb
        name: Optaplanner
      release_notes:
      source:
        size: 154mb
        filename: jboss-bpmsuite-6.0.1.GA-source.zip 
upstream_projects:
  - optaplanner
  - drools
  - guvnor
#  - uberfire
featured_items:
  - image_url: http://design.jboss.org/jbossdeveloper/sitedesign/jbossdeveloper_1_0/makerfiles/images/developermaterials_brms.png
    url: /quickstarts/brms/helloworld-brms

