name: Red Hat OpenJDK
abbreviated_name: OpenJDK
current_version:
product_category: application-development
skip_installation_instructions: true
skip_maven_instructions: true
ignore_forums: true
index:
  desc: |
    A Tried, Tested and Trusted open source implementation of the Java platform
description: 'A Tried, Tested and Trusted open source implementation of the Java platform'
