name: Red Hat Development Suite
abbreviated_name: DevSuite
product_logo: enterprise-app-platform.png
current_version: 7.0.0
documentation_path: red-hat-jboss-enterprise-application-platform
product_category: application-development
youtube_album: https://www.youtube.com/playlist?list=PLf3vm0UK6HKpAr_6VUi6nkoSQDov8fuZg
ignore_forums: true
index:
  desc: |
    A fully integrated development environment for modern enterprise development.
description: 'A fully integrated development environment for modern enterprise development.'
