version: '2'
services:
  awestruct:
    build: ../../awestruct
    command:
      - "rake git_setup clean preview[docker]"
    volumes:
      - ../../../:/home/awestruct/developer.redhat.com
      - ../../awestruct/overlay/ssh-key:/home/awestruct/.ssh
    environment:
      - google_api_key
      - dcp_user
      - dcp_password
      - vimeo_client_secret
      - vimeo_access_token_secret
      - vimeo_access_token
      - cache_password
      - cache_url
      - site_base_path
      - site_path_suffix
      - cdn_prefix
      - cache_user
      - github_token
      - ACCESSIBLE_SLAVE_IP
      - SEARCHISKO_HOST_PORT
      - ghprbActualCommit
      - github_status_api_token
      - BUILD_URL
      - AWE_PROC_COUNT=10

  #
  # Testing
  #
  unit_tests:
   build: ../../awestruct
   volumes:
    - ../../../:/home/awestruct/developer.redhat.com
   entrypoint: "bundle exec rake test"
   environment:
    - google_api_key
    - dcp_user
    - dcp_password
    - vimeo_client_secret
    - vimeo_access_token_secret
    - vimeo_access_token
    - cache_password
    - cache_url
    - site_base_path
    - site_path_suffix
    - cdn_prefix
    - cache_user
    - github_token
    - ACCESSIBLE_SLAVE_IP
    - SEARCHISKO_HOST_PORT
    - ghprbActualCommit
    - github_status_api_token
    - BUILD_URL
    - AWE_PROC_COUNT=10

  acceptance_tests:
    build: ../../awestruct
    volumes:
      - ../../../:/home/awestruct/developer.redhat.com
    links:
      - selhub:hub
    environment:
      - ghprbActualCommit
      - github_status_api_token
      - PARALLEL_TEST
      - CUCUMBER_TAGS
      - SELENIUM_HOST=http://hub:4444/wd/hub
      - RHD_JS_DRIVER
      - RHD_DOCKER_DRIVER
      - BUILD_URL
      - RHD_TEST_PROFILE

  docker_chrome:
   image: selenium/node-chrome
   volumes:
    - /dev/shm:/dev/shm
   environment:
    - HUB_PORT_4444_TCP_ADDR=selhub
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
   depends_on:
    - selhub