name: DevOps
sub_title: Innovate at the speed of open source with DevOps
long_description: "At Red Hat we do Dev, Ops, and DevOps. (Do you have a Brent?  Read the Phoenix Project to find out.)"
icon: icon-rh-icon-control-panel
tags:
  - DevOps
  - CI
  - CD
  - Continuous Delivery
  - Continuous Integration
#left_section_icon: icon-rh-icon-network-personal
#middle_section_icon: icon-rh-icon-lifestyle
#right_section_icon: icon-rh-icon-tools
related_products:
  - openshift
  - eap
primary_promo:
  - title: Explore DevOps
    description: "DevOps involves the combination of cultural change, process automation, and tools to improve your time-to-market. Peruse this site for automation and tools."
    links:
      - name: "Accelerate DevOps with OpenShift."
        url: 'https://www.redhat.com/cms/public/Jaen%20Swart_Devops%20with%20EAP%20and%20Openshift.pdf'
      - name: "Register and learn more about DevOps."
        local_url: '/register'
      - name: "Join us at DevNation in San Francisco, June 2016"
        url: http://www.devnation.org/
    tags:
      - Containers
      - DevOps
secondary_promo:
  - title: What is DevOps Really?
    url: https://blog.openshift.com/what-is-devops-really/
    description: "DevOps isn’t just about tools. It isn’t just about process. It isn’t just about culture. If you’re looking at DevOps through a lens that makes it solely about a single aspect of IT, you’re probably doing it wrong and probably won’t succeed."
    tags:
      - DevOps
      - open source
      - OpenShift
tertiary_tall_promo:
  - title: 'So you want to be a DevOps engineer?'
    local_url: '/video/youtube/iLUs6AqQkro/'
    description: "More than just technology, the journey to DevOps includes becoming more comfortable with collaboration and open communication. Red Hat's Jen Krieger discusses the journey to DevOps."
    tags:
      - Ansible
      - DevOps
tertiary_promo:
  - title: 'Continuous Delivery on OpenShift using Jenkins'
    url: 'https://blog.openshift.com/continuous-delivery-on-openshift/'
    description: "See code promoted across build, dev., QA, and prod."
    tags:
      - Containers
      - DevOps
      - CI/CD
      - Jenkins
  - title: 'Gene Kim: Why Everyone Needs DevOps Now'
    local_url: '/video/youtube/vTxAR8EOc8A'
    description: "View this Gene Kim keynote at DevNation. Do you need DevOps?"
    tags:
      - DevOps
      - DevNation
  - title: 'Continuous delivery with docker containers and Java EE'
    url: 'https://www.redhat.com/en/about/events/continuous-delivery-docker-containers-and-java-ee'
    description: "A hands-on approach to start using Docker in RHEL 7"
    tags:
      - Containers
      - DevOps
      - Java
  - title: 'Using containers for DevOps'
    local_url: '/containers/'
    description: "Containerize your apps, launch into microservices."
    tags:
      - Containers
      - Microservices
right_side_promo:
  - title: Follow Red Hat
    section_1:
      title: "Speed your innovation with DevOps."
      sub_title: "From PaaS to Microservices to Mobile - Red Hat has you covered."
    button:
      label: Get Started
      url: '/devops/overview/'
    section_2:
      title: Technologies
      links:
        - name: Source control
          local_url: '/devops/adoption/#source-control'
        - name: Build tools
          local_url: '/devops/adoption/#tools'
        - name: Continuous delivery
          local_url: '/devops/adoption/#continuous-integration'
        - name: Containers
          local_url: '/devops/adoption/#containers'
        - name: Configuration as code
          local_url: '/devops/adoption/#configuration-as-code'
        - name: Server provisioning
          local_url: '/devops/adoption/#server-provisioning'
        - name: Container orchestration
          local_url: '/devops/adoption/#container-orchestration'
    section_4:
      links:
        - name: Learn
          local_url: '/devops/learn/'
        - name: Buzz
          local_url: '/devops/buzz/'
